### ISSUE TITLE
MonaServer sound

### ISSUE THREAD

**Issue by zhangjie93** [MonaSolutions/MonaServer2#9]
There are problems with the sound .when I use OBS push video(the source is screen) to MonaTiny and VLC to play ,the sound is  always the the first 。the sound repeat again and again

**Comment by MathieuPOUX** [comment]
Hi,

Can you detail your song codec configuration? And the number version of OBS.
I will test it quickly.

**Comment by zhangjie93** [comment]
I use OBS 18.0.1，I do not modify the song codec configuration of the obs and monatiny

**Comment by nobme** [comment]
Hi zhangjie93 . Have you sortes out your issue? 
Could you do a cross test with using MP4 in 'Media Source' as source of stream. If this does not give repeating sound, you have some issue with your sound card / sound setup. 
Some setup let you 'listen to your recording' and this will create an echo sound. 
I'm using BlackMagicDesign as source, OBS to create stream, MonaServer #1 as server, and VLC to receive. Everything work perfect. Had earlier i Firewall issue that cut of sound, Had to add a rulle to FW to fix it... Hope you can fix your system...

**Comment by MathieuPOUX** [comment]
Hi,

Sorry for my delayed response (a lot of work, thanks nobme for your response).
I have just tested now with OBS 19.0.2, and without any configuration change, it streams in Speex codec for audio, everything work fine here. However I regret that OBS looks adds a lot of latency (maybe a OBS configuration to change?).
By this way, do you know that you can publish with VLC too? (supports RTMP publication).

Let me know if it works finally for you zhangjie93 and contact me by hangout otherwise.
Best,
Mathieu

**Comment by nobme** [comment]
Hi zhangjie93. Your are writing that 'sound is coming first' You may adjust this under sound properties (Advanced Audio Properties). Parameter name is 'Sync Offset (mS)'
Try 160 to start with, and test.

**Comment by nobme** [comment]
Hi zhangjie93.
You write that 'Sound is coming first' You may adjust this under Advanced Audio Properties, Parameter name is 'Sync Offset (mS)
Start with 160 and adjust what you need.
